import { LINKEDIN_URL, EMAIL_URL, CALL_URL, WHATSAPP_URL } from './links'
import { EXPERIENCES } from './experience'
import { TAILWIND_BREAKPOINTS, NAVBAR_THEME_MAPPING } from './tailwind'

export { LINKEDIN_URL, EMAIL_URL, CALL_URL, WHATSAPP_URL, TAILWIND_BREAKPOINTS, EXPERIENCES, NAVBAR_THEME_MAPPING };
